# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NIST COBOL85 tests

on: [push]

jobs:
    check-bats-version:
    runs-on: ubuntu-latest
     
    steps:
      - name: Download and Build NIST COBOL85 tests
        run: |
             https://www.itl.nist.gov/div897/ctg/cobol_form.htm
             uncompress newcob.val.Z
        uses: actions/checkout@v3

          
      - name: Install opensource COBOL v1.5.2J
        run: |
            cd opensource-cobol/vbisam
            ./configure --prefix=/usr/
            make
            sudo make install
            cd ../
            ./configure --prefix=/usr/ --with-vbisam
            make
            sudo make install
